### ISSUE TITLE
点login为何不会弹出'login clicked'

### ISSUE THREAD

**Issue by allentofight** [xiabin/CI_Scaffolding#1]
按步骤，login的按钮是出现了，但点login时不会弹出‘login Clicked’,貌似index.js不起作用

PS：我执行npm run dev了

**Comment by xiabin** [comment]
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = 'http://localhost/CI_FastDev';

config/development/config.php  文件里面设置一下 这个base_url 必须设置的 设置成为你的打开路径 就好
